package teeworlds7_test

import (
	"testing"

	"github.com/teeworlds-go/protocol/internal/testutils/require"
	"github.com/teeworlds-go/protocol/messages7"
	"github.com/teeworlds-go/protocol/network7"
	"github.com/teeworlds-go/protocol/object7"
	"github.com/teeworlds-go/protocol/packer"
	"github.com/teeworlds-go/protocol/protocol7"
	"github.com/teeworlds-go/protocol/snapshot7"
	"github.com/teeworlds-go/protocol/teeworlds7"
)

func TestUnpackDelta(t *testing.T) {
	t.Parallel()
	// snapshot captured with tcpdump
	// generated by a vanilla teeworlds 0.7.5 server
	// used the protocol sample client to connect to the server
	//
	// libtw2 dissector details
	// Teeworlds 0.7 Protocol packet
	// Teeworlds 0.7 Protocol chunk: game.sv_game_info
	//     Header (vital: 9)
	//     Message: game.sv_game_info
	//     Game flags: none (0x0)
	//     Score limit: 20
	//     Time limit: 0
	//     Match num: 0
	//     Match current: 1
	// Teeworlds 0.7 Protocol chunk: game.sv_client_info
	//     Header (vital: 10)
	//     Message: game.sv_client_info
	//     Client id: 0
	//     Local: true
	//     Team: red
	//     Name: "nameless tee"
	//     Clan: ""
	//     Country: 0
	//     Skin part names: "greensward"
	//     Skin part names: "duodonny"
	//     Skin part names: ""
	//     Skin part names: "standard"
	//     Skin part names: "standard"
	//     Skin part names: "standard"
	//     Use custom colors: false
	//     Use custom colors: false
	//     Use custom colors: false
	//     Use custom colors: false
	//     Use custom colors: false
	//     Use custom colors: false
	//     Skin part colors: 0
	//     Skin part colors: 0
	//     Skin part colors: 0
	//     Skin part colors: 0
	//     Skin part colors: 0
	//     Skin part colors: 0
	//     Silent: false
	// Teeworlds 0.7 Protocol chunk: sys.snap_single
	//     Header (non-vital)
	//     Message: sys.snap_single
	//     Tick: 1300
	//     Delta tick: 1301
	//     Crc: 2205
	//     Data (45 bytes)
	dump := []byte{
		0x10, 0x04, 0x03, 0x01, 0x02, 0x03, 0x04,
		0x4a, 0x36, 0x4c, 0xed, 0xe1, 0x47, 0xde, 0x6a, 0x3d, 0x8c, 0xd8, 0xb5, 0x73, 0x14, 0x1d,
		0x71, 0x82, 0x2b, 0xc1, 0x09, 0x74, 0x4a, 0xa7, 0xac, 0xa1, 0x84, 0x13, 0x38, 0xe1, 0x74, 0x0e,
		0x4e, 0x9c, 0xc0, 0x09, 0xae, 0x9d, 0x4e, 0x15, 0xb7, 0x1c, 0x05, 0x27, 0x4e, 0xcc, 0x89, 0xb6,
		0xd4, 0x16, 0x71, 0xa2, 0x2d, 0x72, 0xed, 0xae, 0x1d, 0xca, 0xa7, 0x53, 0x28, 0xe1, 0x28, 0xd7,
		0xce, 0x89, 0x1c, 0x05, 0x27, 0x4e, 0x4c, 0xa7, 0x50, 0xc2, 0x51, 0xae, 0x9d, 0x13, 0x39, 0x0a,
		0x4e, 0x9c, 0x98, 0x4e, 0xa1, 0x84, 0xa3, 0x5c, 0x3b, 0x27, 0x72, 0x14, 0x9c, 0x38, 0xf1, 0xff,
		0xcf, 0xd1, 0xa6, 0x0c, 0x78, 0xc5, 0xe0, 0x7d, 0xac, 0xdb, 0xd6, 0x5e, 0x9b, 0xb1, 0x7e, 0x93,
		0x72, 0x58, 0xef, 0x2b, 0xfd, 0xfa, 0x7a, 0xbc, 0x7f, 0x32, 0xb7, 0x49, 0x39, 0xac, 0xa7, 0xb8,
		0x01,
	}

	// 1st snap ->   13	0.071199	8303	41371	TW7	177	game.sv_game_info, game.sv_client_info, sys.snap_single
	//               14	0.080666	41371	8303	TW7	67	sys.input
	//               15	0.111582	8303	41371	TW7	115	sys.input_timing, sys.snap_single

	conn := protocol7.Session{}

	packet := protocol7.Packet{}
	err := packet.Unpack(dump)
	require.NoError(t, err)

	conn.Ack = packet.Header.Ack
	// TODO: one day this should work
	// repack := packet.Pack(&conn)
	// require.Equal(t, dump, repack)

	// content
	require.Equal(t, 3, len(packet.Messages))
	require.Equal(t, network7.MsgSysSnapSingle, packet.Messages[2].MsgId())
	msg, ok := packet.Messages[2].(*messages7.SnapSingle)
	require.Equal(t, true, ok)

	// unverified
	require.Equal(t, 4, msg.Snapshot.NumItemDeltas)
	require.Equal(t, 0, msg.Snapshot.NumRemovedItems)
	require.Equal(t, 4, len(msg.Snapshot.Items))

	// matches libtw2
	require.Equal(t, 2205, msg.Snapshot.Crc)

	// unverified
	item := msg.Snapshot.Items[0]
	require.Equal(t, network7.ObjGameData, item.TypeId())
	gameData, ok := item.(*object7.GameData)
	require.Equal(t, true, ok)
	require.Equal(t, 0, gameData.Id())
	require.Equal(t, 0, gameData.GameStartTick)
	require.Equal(t, 1, gameData.FlagsRaw)
	require.Equal(t, 0, gameData.GameStateEndTick)

	item = msg.Snapshot.Items[1]
	require.Equal(t, network7.ObjCharacter, item.TypeId())
	character, ok := item.(*object7.Character)
	require.Equal(t, true, ok)
	require.Equal(t, 0, character.Id())
	require.Equal(t, 0, character.Tick)
	require.Equal(t, 784, character.X)
	require.Equal(t, 304, character.Y)
	require.Equal(t, 0, character.VelX)
	require.Equal(t, 0, character.VelY)
	require.Equal(t, 0, character.Angle)
	require.Equal(t, 0, character.Direction)
	require.Equal(t, 0, character.Jumped)
	require.Equal(t, -1, character.HookedPlayer)
	require.Equal(t, 0, character.HookState)
	require.Equal(t, 0, character.HookTick)
	require.Equal(t, 0, character.HookX)
	require.Equal(t, 0, character.HookY)
	require.Equal(t, 0, character.HookDx)
	require.Equal(t, 0, character.HookDy)
	require.Equal(t, 10, character.Health)
	require.Equal(t, 0, character.Armor)
	require.Equal(t, 10, character.AmmoCount)
	require.Equal(t, network7.WeaponGun, character.Weapon)
	require.Equal(t, network7.EyeEmoteNormal, character.Emote)
	require.Equal(t, 0, character.AttackTick)
	require.Equal(t, 0, character.TriggeredEvents)

	item = msg.Snapshot.Items[2]
	require.Equal(t, network7.ObjPlayerInfo, item.TypeId())
	playerInfo, ok := item.(*object7.PlayerInfo)
	require.Equal(t, 8, playerInfo.PlayerFlags)
	require.Equal(t, 0, playerInfo.Score)
	require.Equal(t, 0, playerInfo.Latency)

	// ------------------------------------
	// client with state and delta unpacker
	// ------------------------------------

	client := teeworlds7.NewClient()

	deltaTick := msg.GameTick - msg.DeltaTick
	prevSnap, err := client.SnapshotStorage.Get(deltaTick)
	require.NoError(t, err)

	u := &packer.Unpacker{}
	u.Reset(msg.Data)

	newFullSnap, err := snapshot7.UnpackDelata(prevSnap, u)
	require.NoError(t, err)

	err = client.SnapshotStorage.Add(msg.GameTick, newFullSnap)
	require.NoError(t, err)

	client.SnapshotStorage.PurgeUntil(deltaTick)

	// Teeworlds 0.7 Protocol packet
	// Teeworlds 0.7 Protocol chunk: game.sv_game_info
	//     Header (vital: 9)
	//         Flags: vital (01.. ....)
	//         Size: 6 bytes (..00 0000 ..00 0110)
	//         Sequence number: 9 (00.. .... 0000 1001)
	//     Message: game.sv_game_info
	//         .... ...0 = Game message
	//         Raw message ID: 19
	//     Game flags: none (0x0)
	//         .... ...0 = NOT teams
	//         .... ..0. = NOT flags
	//         .... .0.. = NOT survival
	//         .... 0... = NOT race
	//     Score limit: 20
	//     Time limit: 0
	//     Match num: 0
	//     Match current: 1
	// Teeworlds 0.7 Protocol chunk: game.sv_client_info
	//     Header (vital: 10)
	//         Flags: vital (01.. ....)
	//         Size: 80 bytes (..00 0001 ..01 0000)
	//         Sequence number: 10 (00.. .... 0000 1010)
	//     Message: game.sv_client_info
	//         .... ...0 = Game message
	//         Raw message ID: 18
	//     Client id: 0
	//     Local: true
	//     Team: red
	//     Name: "nameless tee"
	//     Clan: ""
	//     Country: 0
	//     Skin part names: "greensward"
	//     Skin part names: "duodonny"
	//     Skin part names: ""
	//     Skin part names: "standard"
	//     Skin part names: "standard"
	//     Skin part names: "standard"
	//     Use custom colors: false
	//     Use custom colors: false
	//     Use custom colors: false
	//     Use custom colors: false
	//     Use custom colors: false
	//     Use custom colors: false
	//     Skin part colors: 0
	//     Skin part colors: 0
	//     Skin part colors: 0
	//     Skin part colors: 0
	//     Skin part colors: 0
	//     Skin part colors: 0
	//     Silent: false
	// Teeworlds 0.7 Protocol chunk: sys.snap_single
	//     Header (non-vital)
	//         Flags: none (00.. ....)
	//         Size: 53 bytes (..00 0000 ..11 0101)
	//     Message: sys.snap_single
	//         .... ...1 = System message
	//         Raw message ID: 8
	//     Tick: 1300
	//     Delta tick: 1301
	//     Crc: 2205
	//     Data (45 bytes)
	dump = []byte{
		0x10, 0x04, 0x03, 0x01, 0x02, 0x03, 0x04,
		0x4a, 0x36, 0x4c, 0xed, 0xe1, 0x47, 0xde, 0x6a, 0x3d, 0x8c, 0xd8, 0xb5, 0x73, 0x14, 0x1d,
		0x71, 0x82, 0x2b, 0xc1, 0x09, 0x74, 0x4a, 0xa7, 0xac, 0xa1, 0x84, 0x13, 0x38, 0xe1, 0x74, 0x0e,
		0x4e, 0x9c, 0xc0, 0x09, 0xae, 0x9d, 0x4e, 0x15, 0xb7, 0x1c, 0x05, 0x27, 0x4e, 0xcc, 0x89, 0xb6,
		0xd4, 0x16, 0x71, 0xa2, 0x2d, 0x72, 0xed, 0xae, 0x1d, 0xca, 0xa7, 0x53, 0x28, 0xe1, 0x28, 0xd7,
		0xce, 0x89, 0x1c, 0x05, 0x27, 0x4e, 0x4c, 0xa7, 0x50, 0xc2, 0x51, 0xae, 0x9d, 0x13, 0x39, 0x0a,
		0x4e, 0x9c, 0x98, 0x4e, 0xa1, 0x84, 0xa3, 0x5c, 0x3b, 0x27, 0x72, 0x14, 0x9c, 0x38, 0xf1, 0xff,
		0xcf, 0xd1, 0xa6, 0x0c, 0x78, 0xc5, 0xe0, 0x7d, 0xac, 0xdb, 0xd6, 0x5e, 0x9b, 0xb1, 0x7e, 0x93,
		0x72, 0x58, 0xef, 0x2b, 0xfd, 0xfa, 0x7a, 0xbc, 0x7f, 0x32, 0xb7, 0x49, 0x39, 0xac, 0xa7, 0xb8,
		0x01,
	}

	//               13	0.071199	8303	41371	TW7	177	game.sv_game_info, game.sv_client_info, sys.snap_single
	//               14	0.080666	41371	8303	TW7	67	sys.input
	// 2nd snap ->   15	0.111582	8303	41371	TW7	115	sys.input_timing, sys.snap_single

	packet = protocol7.Packet{}
	err = packet.Unpack(dump)
	require.NoError(t, err)

	// WOAH THERE! this should be 2
	require.Equal(t, 3, len(packet.Messages))

	// require.Equal(t, network7.MsgSysSnapSingle, packet.Messages[1].MsgId())
	// msg, ok = packet.Messages[1].(*messages7.SnapSingle)
	// require.Equal(t, true, ok)

	// // unverified
	// require.Equal(t, 000000000, msg.Snapshot.NumItemDeltas)
	// require.Equal(t, 000000000, msg.Snapshot.NumRemovedItems)
	// require.Equal(t, 000000000, len(msg.Snapshot.Items))
}
